# Generated by Django 3.2.8 on 2021-11-11 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mission',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('url', models.TextField(verbose_name='入口链接')),
                ('domain', models.TextField(verbose_name='域')),
            ],
            options={
                'verbose_name': '任务信息',
                'verbose_name_plural': '任务库',
            },
        ),
        migrations.CreateModel(
            name='linksData',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('link', models.TextField(null=True, verbose_name='链接')),
                ('response_code', models.IntegerField(verbose_name='响应状态码')),
                ('abnormal', models.BooleanField(verbose_name='是否异常')),
                ('abnormal_point', models.BooleanField(verbose_name='异常点')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='getlinksapp.mission')),
            ],
            options={
                'verbose_name': '链接信息',
                'verbose_name_plural': '链接库',
            },
        ),
    ]
