# Generated by Django 3.2.8 on 2021-11-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getlinksapp', '0002_alter_linksdata_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksdata',
            name='find_time',
            field=models.TimeField(null=True, verbose_name='发现时间'),
        ),
    ]
