# Generated by Django 3.2.8 on 2021-11-11 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getlinksapp', '0005_alter_linksdata_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='domainTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField(blank=True, null=True, verbose_name='域')),
            ],
            options={
                'verbose_name': '域信息',
                'verbose_name_plural': '域库',
            },
        ),
        migrations.AlterField(
            model_name='mission',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domainTable', to='getlinksapp.domaintable', verbose_name='域'),
        ),
    ]
