# Generated by Django 3.2.8 on 2021-11-11 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getlinksapp', '0006_auto_20211111_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksdata',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domainTable1', to='getlinksapp.domaintable', verbose_name='域'),
        ),
    ]
