# Generated by Django 3.2.8 on 2021-11-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getlinksapp', '0007_alter_linksdata_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksdata',
            name='from_link',
            field=models.TextField(blank=True, null=True, verbose_name='发现页面'),
        ),
    ]
