# Generated by Django 3.2.8 on 2021-11-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getlinksapp', '0008_linksdata_from_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksdata',
            name='abnormal_point',
            field=models.TextField(blank=True, null=True, verbose_name='异常点'),
        ),
    ]
