# Generated by Django 3.2.8 on 2021-11-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getlinksapp', '0009_alter_linksdata_abnormal_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksdata',
            name='find_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发现时间'),
        ),
    ]
