# Generated by Django 3.2.8 on 2021-12-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getlinksapp', '0010_alter_linksdata_find_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('file_name', models.FileField(upload_to='xlsfile/%Y/%m/%d/', verbose_name='文件名称')),
            ],
            options={
                'verbose_name': '用例文件管理',
                'verbose_name_plural': '用例文件管理',
            },
        ),
    ]
