# Generated by Django 3.2.8 on 2022-01-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getlinksapp', '0011_casefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casefile',
            options={'verbose_name': '文件管理', 'verbose_name_plural': '文件管理'},
        ),
        migrations.AlterModelOptions(
            name='linksdata',
            options={'verbose_name': '链接信息', 'verbose_name_plural': '扫描结果'},
        ),
    ]
