# Generated by Django 3.2.8 on 2022-04-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getlinksapp', '0012_auto_20220106_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domaintable',
            options={'verbose_name': '域名信息', 'verbose_name_plural': '域名库'},
        ),
        migrations.AlterField(
            model_name='domaintable',
            name='domain',
            field=models.CharField(blank=True, default='新建比赛', max_length=40, null=True, verbose_name='域名（每次只能一个，没有其他说法！）'),
        ),
    ]
