# Generated by Django 3.2.8 on 2022-04-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getlinksapp', '0013_auto_20220406_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaintable',
            name='domain',
            field=models.CharField(blank=True, default='只能填一个！示例：www.tsinghua.edu.cn', max_length=40, null=True, verbose_name='域名（每次只能一个，没有其他说法！）'),
        ),
    ]
