# Generated by Django 3.2.8 on 2022-04-06 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getlinksapp', '0015_alter_domaintable_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaintable',
            name='domain',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domainTable', to='getlinksapp.domaintable', verbose_name='扫描的域名'),
        ),
    ]
