# Generated by Django 3.2.8 on 2022-04-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getlinksapp', '0016_auto_20220406_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linksdata',
            name='abnormal',
        ),
        migrations.AlterField(
            model_name='domaintable',
            name='domain',
            field=models.CharField(blank=True, default='只能填一个域名！示例：www.tsinghua.edu.cn', max_length=100, null=True, verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='linksdata',
            name='abnormal_point',
            field=models.CharField(blank=True, default=None, max_length=9999, null=True, verbose_name='异常点'),
        ),
        migrations.AlterField(
            model_name='linksdata',
            name='from_link',
            field=models.CharField(blank=True, default=None, max_length=9999, null=True, verbose_name='发现页面'),
        ),
        migrations.AlterField(
            model_name='linksdata',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=9999, null=True, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='url',
            field=models.CharField(blank=True, default='只是作为扫描任务的入口！示例：http://www.tsinghua.edu.cn/index.html', max_length=100, null=True, verbose_name='任务开始链接（扫描由此开始）'),
        ),
    ]
